### ISSUE TITLE
CSV file in video corpus missing

### ISSUE THREAD

**Issue by genekogan** [jazzsaxmafia/video_to_sequence#2]
There doesn't seem to be a CSV file in [Microsoft Video Description Corpus](http://research.microsoft.com/en-us/downloads/38cf15fd-b8df-477e-a4e4-a4680caa75af/).  I downloaded the MSI and there are a number of files in it, none appear to be CSV. Is it one of the included files?
<img width="751" alt="screen shot 2015-12-28 at 4 06 34 pm" src="https://cloud.githubusercontent.com/assets/1335251/12025443/14589442-ad7d-11e5-98d3-77afc4c63b63.png">

**Comment by jazzsaxmafia** [comment]
Hi. Did you try to install the .MSI file under ms windows environment? Seems like you opened the .MSI file from other OS system.

**Comment by jazzsaxmafia** [comment]
If you still have trouble after that, let me know and I will sent you the file.

**Comment by genekogan** [comment]
no, i opened it in Mac OS and it simply unzipped the files. is there another way to obtain the file?

**Comment by genekogan** [comment]
yes that would be great if you could make it available. perhaps storing it online somewhere (like archive.org) would be useful for others.

**Comment by genekogan** [comment]
if anyone else is having trouble finding this file, feel free to email me and i can send it.

**Comment by andyyuan78** [comment]
@genekogan

would you like sent a copy to me? thanks
andyyuan78@gmail.com

**Comment by Joon370** [comment]
@genekogan 
would  you like send a file "video_corpus.csv"  to me ? thanks alot
duqkd07@naver.com

**Comment by fodrh1201** [comment]
@genekogan 

Hi genekogan.
would you like send me a copy?
because I use mac, I cannot open .msi file.
thanks.

fodrh1201@gmail.com

**Comment by genekogan** [comment]
@fodrh1201 @andyyuan78 and for anyone else, the corpus can be downloaded here: 
[video_corpus.csv.zip](https://github.com/jazzsaxmafia/video_to_sequence/files/387979/video_corpus.csv.zip)

**Comment by adrienj** [comment]
Also some of the Microsoft Video Description Corpus clips are not available on youtube anymore but here's the full archive: 
https://www.cs.utexas.edu/users/ml/clamp/videoDescription/YouTubeClips.tar (1.7GB)
from https://www.cs.utexas.edu/users/ml/clamp/videoDescription/#data.

**Comment by AmmieQi** [comment]
@genekogan Thank you very much!
