### ISSUE TITLE
Why the generated sentence missed last word?

### ISSUE THREAD

**Issue by yidijimao100** [jazzsaxmafia/video_to_sequence#5]
It seems that the plane example "a plane is flying in the ." missed some words, and so as to my training, does something wrong? below is some ones I get using test:
    a man is talking to a .
    a man is talking about the . 
    a woman is showing how to use a .
    a man is talking about a .
    a man is talking about a video .
    a man is talking about a .
    a man is driving a car and talking about .
    a football player runs down the .
    a person is solving a rubik's .
    a man is talking about the .
    a man is talking to another man about .
    a man is singing a .
    a man is jumping on a .
    a man is talking to another man in a .
    a woman is showing a .

**Comment by jazzsaxmafia** [comment]
Hello,

My results also suffered that phenomenon. I was going to find out what I
did wrong but totally forgot until now.

Let me find out what went wrong, and I will let you know.
Thank you for reminding me.

-Taeksoo

2016-05-27 15:29 GMT+09:00 yidijimao100 notifications@github.com:

**Comment by yidijimao100** [comment]
Hello  jazzsaxmafia,

Whether or not because of missing EOS (".") ?
In train(), it is erased by "captions = map(lambda x: x.replace('.', ''), captions)"
I am trying to modify it.

**Comment by yidijimao100** [comment]
@jazzsaxmafia 

I have modified it by adding " ." at the end of each sentence, and the generated one seems correct.

**Comment by jazzsaxmafia** [comment]
Wow, thank you for the job!
Could you please make a pull request?
-Taeksoo
2016. 6. 1. 오전 10:46에 "yidijimao100" notifications@github.com님이 작성:

**Comment by yidijimao100** [comment]
@jazzsaxmafia

The code "captions = map(lambda x: x.replace('.', ''), captions)" in line 222 of "model.py" deleted ".", and then line 268 erased last word again. So the last word of training captions is lost. 

I just modified line 268 to:
"current_caption_ind = map(lambda cap: [wordtoix[word] for word in cap.lower().split(' ') if word in wordtoix], current_captions)"

**Comment by jazzsaxmafia** [comment]
That makes sense. I will change the line.

Thank you again for your commitment.

-Taeksoo
2016. 6. 1. 오후 6:59에 "yidijimao100" notifications@github.com님이 작성:
